spring.application.name=notification-service
server.port=8084


# Database Configuration (Port 3307 for XAMPP)
spring.datasource.url=jdbc:mysql://localhost:3307/db_notification?useSSL=false
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Email Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sasumanakusha@gmail.com
# IMPORTANT: Use a generated App Password here, NOT your normal Gmail password
spring.mail.password=ddwu egne jufr kead

# Advanced Mail Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/